VAGRANTFILE_API_VERSION = "2"
Vagrant.configure("2") do |config|
  # Building on ubuntu trusty box
  config.vm.box = "ubuntu/trusty64" 


  # Configuring the machine with at least 1 GB of memory, 2 cpus
  # These could be commented and are optional but the vm will work better with it
  config.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id,'--memory', '1024']
      vb.customize ["modifyvm", :id, "--cpus"  , "2"   ]
  end


  # Configuring the main machine
  config.vm.define "django-vm", autostart: true  do |server|
    server.vm.hostname = "django-vm"
    server.vm.box = "ubuntu/trusty64"
    server.vm.network :private_network, ip: "192.168.66.2"
    server.hostsupdater.aliases = [ "django.dev.machine"]
  end





  config.vm.provision "shell" do |script|
    script.path = "./provision.sh"
    end


end
