VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # All vms Settings, More juice, Better VMS
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id,'--memory', '2048'] # memory to vm
    vb.customize ["modifyvm", :id, "--cpus", 4] # number of cpu cores
    vb.customize ["modifyvm", :id, "--paravirtprovider", 'kvm' ] # can be set to "paravirt"
    vb.customize ["modifyvm", :id, "--ioapic", "on"] # turn on I/O APIC  end
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"] # Enabling DNS proxy in NAT mode
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"] # Using the host's resolver as a DNS proxy in NAT mode
    end


  # Salt Master VM
  config.vm.define "saltmaster", autostart: true  do |server|
    server.vm.hostname = "saltmaster.machine"
    server.vm.box = "ubuntu/trusty64"
    server.vm.network :private_network, ip: "192.168.66.66"

    # synx salt master states
    config.vm.synced_folder "salt/", "/srv/salt"


    # install and configure salt
    config.vm.provision "shell" do |script|
      script.path = "./provisioning/master_provisioner.sh"
      end

    end



  # Salt Minion VM
  config.vm.define "saltminion", autostart: true  do |server|
    server.vm.hostname = "saltminion.machine"
    server.vm.box = "ubuntu/trusty64"

    server.vm.network :private_network, ip: "192.168.66.67"

    # provision
    config.vm.provision "shell" do |script|
      script.path = "./provisioning/minion_provisioner.sh"
      end
    end



end
