VAGRANTFILE_API_VERSION = "2"
Vagrant.configure("2") do |config|

  # Configuring the machine with at least 1 GB of memory
  config.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id,'--memory', '512']
      vb.customize ["modifyvm", :id, "--cpus"  , "2"  ]
  end



  config.vm.define "saltmaster", autostart: true  do |server|
    server.vm.hostname = "saltmaster.machine"
    server.vm.box = "ubuntu/trusty64"
    server.vm.network :private_network, ip: "192.168.66.66"
    end



# sync saltmaster configs
config.vm.synced_folder "etc-salt/", "/etc/salt/"
# synx salt master states
config.vm.synced_folder "srv-salt/", "/srv/salt/"

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.provision "shell" do |script|
    script.path = "./provision.sh"
    end



end
